[package]
name = "generator"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.88"


[dependencies]
anyhow = "1.0.96"
log = "0.4"
flexi_logger = "0.30.1"
chrono = "0.4.31"
hex = "0.4.3"
byteorder = "1.5.0"
rand = "0.9.0"
iced-x86 = "1.21.0"