[package]
name = "packet_processor_macro"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.85"

[dependencies]
syn = { version = "2.0.100", features = ["extra-traits"] }
quote = "1.0.40"
proc-macro2 = "1.0.94"

[lib]
proc-macro = true