[package]
name = "rust_playground"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.85"

[lib]
name = "rust_playground_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tokio = { version = "1.41.0", features = ["rt", "macros"] }
tauri = { version = "2.2.5", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.38", features = ["serde"] }
thiserror = "2.0.12"
log = "0.4.22"
sqlx = { version = "0.8.5", features = [ "runtime-tokio", "sqlite", "uuid", "chrono" ] }
anyhow = "1.0.96"
uuid = { version = "1", features = ["v4"] }
