[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.copy_dll]
cwd = ".."
script_runner = "powershell"
script_extension = "ps1"
script = '''
Copy-Item dll_lib\\target\\debug\\dll_lib.dll wrapper\\dll_lib.dll
Copy-Item wrapper\\dll_lib.dll wrapper\\target\\debug\\dll_lib.dll
'''

[tasks.build_and_copy]
dependencies = [
    "build",
    "copy_dll"
]

[tasks.run_wrapper]
command = "cargo"
args = ["run", "-p", "wrapper"]