[package]
name = "crossterm_table"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.85"

[dependencies]
anyhow = "1.0.96"
crossterm = "0.29.0"
rand = "0.9.0"
chrono = "0.4.31"
strum = "0.27"
strum_macros = "0.27"
uuid = { version = "1", features = ["v7"] }