[package]
name = "library"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.85"

[lib]
crate-type = ["cdylib",'rlib']

[dependencies]
anyhow = "1.0.96"
shared = { path = "../shared" }
abi_stable = "0.11.3"
rand = "0.9.0"
tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread", "signal", "time", "sync", "macros"] }