[package]
name = "tauri_unit_tests"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.85"

[dependencies]
tauri = { version = "2.2.5", features = ["tray-icon"] }

[dev-dependencies]
mockall = "0.13.1"