[package]
name = "thread_communication"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.85"

[dependencies]
log = "0.4"
simple_logger = "5.0.0"
rand = "0.9.0"
chrono = "=0.4.38"
anyhow = "1.0.96"
multiqueue = "0.3.2"