name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - shell: pwsh
        run: |
          Write-Host "Current directory: $(Get-Location)"
      - shell: pwsh
        run: .\.github\scripts\ci.ps1
