
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: edgarrc/action-7z@v1
      - run: 7z x encrypted_project.7z -odecrypted_project -p"@\r]?)4y~'E<£)954FfQD348}"
      - run: cargo build --release
        working-directory: decrypted_project
