[package]
name = "leptos-template"
version = "0.1.0"
authors = ["Jozef Podlecki"]
edition = "2018"
rust-version = "1.84"

[dependencies]
duckdb = { version = "1.1.1", features = ["bundled", "r2d2"] }
r2d2 = "0.8.10"